Controllers/HomeController.cs
using ITI_Project.Enitties;
using ITI_Project.Models;
using ITI_Project.Models.Repository;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Linq;

namespace ITI_Project.Controllers
{
	public class HomeController : Controller
	{
        Context db = new Context();
        public ProductsContainer container = new ProductsContainer();
        public UserRepo userRepo;
        public SellerRepo SellerRepo;
        //public UserDBRepo userRepo = new UserDBRepo();
        //public SellerDBRepo SellerRepo = new SellerDBRepo();
        public static int Currentid = -1;
        public HomeController()
        {
            SellerRepo = SellerRepo.GetInstance();
            userRepo = UserRepo.GetInstance();
        }

        public IActionResult Login()
		{
			return View();
		}

		[HttpPost]
        public ActionResult Login(Person person)
        {
			var users = userRepo.list();
			var sellers = SellerRepo.list();
            //check if the person is user
            if(person.role == "user")
            {
                foreach (var item in users)
                {
                    //check if the login is correct 
                    if (item.Name == person.Name && item.Password == person.Password)
                    {
                        person.Id = item.Id;
                        Currentid = item.Id;
                        return RedirectToAction("UserIndex", person);
                    }
                }
                ViewBag.wronglog = "please check username or password and try again";
                return View();
            }
            //check if the person is seller
            else if (person.role == "seller")
            {
                foreach (var item in sellers)
                {
                    if (item.Name == person.Name && item.Password == person.Password)
                    {
                        person.Id = item.Id;
                        Currentid = item.Id;
                        return RedirectToAction("SellerIndex", person);
                    }
                }
                ViewBag.wronglog = "please check username or password and try again";
                return View();
            }
            //if the user didnot choose role
            else
            {
                ViewBag.wronglog = "please choose the role";
                return View();
            }
        }
        public IActionResult UserIndex(Person person)
        {
            
            return View(container.Products);
        }
        public IActionResult SellerIndex(Person person)
        {
            var products = SellerRepo.find(person.Id).Products;
            ViewBag.sellerid = person.Id;
            return View(products);
        }
    }
}

Controllers/SellerController.cs
using ITI_Project.Models;
using ITI_Project.Models.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;
using ITI_Project.Enitties;

namespace ITI_Project.Controllers
{
    public class SellerController : Controller
    {
        Context db = new Context();
        public SellerRepo SellerRepo;
        public ProductRepo ProductRepo;
        //public ProductDBRepo ProductRepo = new ProductDBRepo();
        //public SellerDBRepo SellerRepo = new SellerDBRepo();
        IHostingEnvironment hosting;

        public SellerController( IHostingEnvironment hosting)
        {
            this.SellerRepo = SellerRepo.GetInstance();
            this.ProductRepo = ProductRepo.GetInstance();
            this.hosting = hosting;
        }

        public ActionResult Index(int id)
        {
            id = HomeController.Currentid;
            Person p = SellerRepo.find(id);
            return RedirectToAction("SellerIndex", "Home", p);
        }
        // GET: SellerController/Details/5
        public ActionResult Details(int id)
        {
            var seller = SellerRepo.find(id);
            return View(seller);
        }

        // GET: SellerController/Edit/5
        public ActionResult EditSeller(int id)
        {
            var seller = SellerRepo.find(id);
            return View(seller);
        }

        // POST: SellerController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditSeller(Person seller)
        {
            try
            {
                SellerRepo.update(seller);
                return RedirectToAction("Details", new { seller.Id });
            }
            catch
            {
                return View();
            }
        }

        public ActionResult EditProduct(int id)
        {
            var product = ProductRepo.findbyseller(id, HomeController.Currentid);
            return View(product);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditProduct(Product product)
        {
            try
            {

                if (product.file != null)
                {
                    //to make evry file name unique
                    string name = product.file.FileName + DateTime.Now.ToString("yyyyMMdd_HHmmss") + Path.GetExtension(product.file.FileName);

                    string newpath = preppath(name);
                    //imgUrl is old one
                    string oldpath = preppath(product.ImageUrl);
                    //delete the old file
                    //System.IO.File.Delete(oldpath);

                    //save new file then release the resources
                    FileStream f;
                    product.file.CopyTo(f = new FileStream(newpath, FileMode.Create));
                    f.Dispose();

                    //now imgUrl is new one
                    product.ImageUrl = name;

                }
                ProductRepo.update(product);
                return RedirectToAction("Index", HomeController.Currentid);
            }
            catch
            {
                return View();
            }
        }


        // GET: SellerController/Create
        public ActionResult CreateProduct()
        {
            ViewBag.sellerid = HomeController.Currentid;
            return View();
        }

        // POST: SellerController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateProduct(Product product)
        {
            try
            {
                if (product.file != null)
                {
                    //to make evry file name unique
                    string name = product.file.FileName + DateTime.Now.ToString("yyyyMMdd_HHmmss") + Path.GetExtension(product.file.FileName);

                    //save new file then release the resources
                    FileStream f;
                    product.file.CopyTo(f = new FileStream(preppath(name), FileMode.Create));
                    f.Dispose();

                    product.ImageUrl = name;
                }

                ProductRepo.add(product);
                SellerRepo.find(product.PersonId).Products.Add(product);
                return RedirectToAction("Index", HomeController.Currentid);
            }
            catch
            {
                return View();
            }
        }

        // GET: SellerController/Delete/5
        public ActionResult DeleteProduct(int id)
        {
            var product = ProductRepo.findbyseller(id, HomeController.Currentid);
            return View(product);
        }

        // POST: SellerController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteProduct(Product product)
        {
            try
            {
                var p = ProductRepo.find(product.Id);
                string path = ProductRepo.find(product.Id).ImageUrl;
                path = preppath(path);
                ProductRepo.delete(product.Id);
                SellerRepo.find(HomeController.Currentid).Products.Remove(p);

                //delete file only when delete the developer successfully 
                System.IO.File.Delete(path);


                return RedirectToAction("Index", HomeController.Currentid);
            }
            catch
            {
                return View();
            }
        }
        //handle the path
        string preppath(string name)
        {
            //handle the root path
            string uploads = Path.Combine(hosting.WebRootPath, "assets");

            string fullpath = Path.Combine(uploads, name);

            return fullpath;
        }
    }
}

Controllers/UserController.cs
using ITI_Project.Enitties;
using ITI_Project.Models;
using ITI_Project.Models.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;

namespace ITI_Project.Controllers
{
    public class UserController : Controller
    {
        Context db = new Context();
        public UserRepo UserRepo;
        public ProductRepo ProductRepo;
        public CartRepo CartRepo;
        //public ProductDBRepo ProductRepo = new ProductDBRepo();
        //public UserDBRepo UserRepo = new UserDBRepo();
        //public CartDBRepo CartRepo = new CartDBRepo();
        public UserController() 
        {
            UserRepo = UserRepo.GetInstance();
            ProductRepo = ProductRepo.GetInstance();
            CartRepo = CartRepo.GetInstance();
        }
        // GET: UserController
        public ActionResult Index()
        {
            Person p = UserRepo.find(HomeController.Currentid);
            return RedirectToAction("UserIndex", "Home", p);
        }

        public ActionResult Search(string term)
        {
            if(term == null)
            {
                return View();
            }
            else
            {
                var products = ProductRepo.search(term);
                return View(products);
            }
            
        }

        public ActionResult AddToCart(int productid)
        {
            var user = UserRepo.find(HomeController.Currentid);
            var product = ProductRepo.find(productid);
            if(ProductRepo.find(productid).Quantity > 0)
            {
                ProductRepo.find(productid).Quantity--;
                CartRepo.find(user.CartID).Products.Add(product);
                //user.Cart.Products.Add(product);

                CartRepo.find(user.CartID).Total += product.Price;
                //user.Cart.Total += product.Price;
            }

            return RedirectToAction("Index");
        }

        public ActionResult ViewCart()
        {
            var user = UserRepo.find(HomeController.Currentid);
            var cart = CartRepo.find(user.CartID);
            return View(cart);
        }

        public ActionResult DeleteFromCart(int productid)
        {
            var user = UserRepo.find(HomeController.Currentid);
            var product = ProductRepo.find(productid);

            product.Quantity++;

            //user.Cart.Total -= product.Price;
            CartRepo.find(user.CartID).Total -= product.Price;

            //user.Cart.Products.Remove(product);
            CartRepo.find(user.CartID).Products.Remove(product);

            return RedirectToAction("ViewCart");
        }

        public ActionResult Checkout()
        {
            var user = UserRepo.find(HomeController.Currentid);

            //user.Cart.Products.Clear();
            CartRepo.find(user.CartID).Products.Clear();

            //user.Cart.Total = 0;
            CartRepo.find(user.CartID).Total = 0;

            //return RedirectToAction("ViewCart");
            return View();
        }
    }
}

Views/Home/Login.cshtml
@model Person
@{
    Layout = null;
    ViewData["Title"] = "Home Page";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Design by foolishdeveloper.com -->
    <title> login </title>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <!--Stylesheet-->
    <style media="screen">
        /* Style for the select element */
        .custom-select {
            appearance: none; /* Remove default appearance */
            padding: 5px;
            font-size: 16px;
            border: 1px solid #ccc;
            border-radius: 5px;
            background-color: #fff;
            color: black;
            width: 100%;
            max-width: 300px; /* Adjust as needed */
        }

            /* Style for the options */
            .custom-select option {
                color: black;
            }

                /* Style for the selected option */
                .custom-select option:checked {
                    background-color: #f1f1f1; /* Highlight the selected option */
                }
        *,
        *:before,
        *:after {
            padding: 0;
            margin: 0;
            box-sizing: border-box;
        }

        body {
            background-color: #080710;
        }

        .background {
            width: 430px;
            height: 520px;
            position: absolute;
            transform: translate(-50%,-50%);
            left: 50%;
            top: 50%;
        }

            .background .shape {
                height: 200px;
                width: 200px;
                position: absolute;
                border-radius: 50%;
            }

        .shape:first-child {
            background: linear-gradient( #1845ad, #23a2f6 );
            left: -80px;
            top: -80px;
        }

        .shape:last-child {
            background: linear-gradient( to right, #ff512f, #f09819 );
            right: -30px;
            bottom: -80px;
        }

        form {
            height: 520px;
            width: 400px;
            background-color: rgba(255,255,255,0.13);
            position: absolute;
            transform: translate(-50%,-50%);
            top: 50%;
            left: 50%;
            border-radius: 10px;
            backdrop-filter: blur(10px);
            border: 2px solid rgba(255,255,255,0.1);
            box-shadow: 0 0 40px rgba(8,7,16,0.6);
            padding: 50px 35px;
        }

            form * {
                font-family: 'Poppins',sans-serif;
                color: #ffffff;
                letter-spacing: 0.5px;
                outline: none;
                border: none;
            }

            form h3 {
                font-size: 32px;
                font-weight: 500;
                line-height: 42px;
                text-align: center;
            }

        label {
            display: block;
            margin-top: 30px;
            font-size: 16px;
            font-weight: 500;
        }

        input {
            display: block;
            height: 50px;
            width: 100%;
            background-color: rgba(255,255,255,0.07);
            border-radius: 3px;
            padding: 0 10px;
            margin-top: 8px;
            font-size: 14px;
            font-weight: 300;
        }

        ::placeholder {
            color: #e5e5e5;
        }

        button {
            margin-top: 50px;
            width: 100%;
            background-color: #ffffff;
            color: #080710;
            padding: 15px 0;
            font-size: 18px;
            font-weight: 600;
            border-radius: 5px;
            cursor: pointer;
        }

        .social {
            margin-top: 30px;
            display: flex;
        }

            .social div {
                background: red;
                width: 150px;
                border-radius: 3px;
                padding: 5px 10px 10px 5px;
                background-color: rgba(255,255,255,0.27);
                color: #eaf0fb;
                text-align: center;
            }

                .social div:hover {
                    background-color: rgba(255,255,255,0.47);
                }

            .social .fb {
                margin-left: 25px;
            }

            .social i {
                margin-right: 4px;
            }

    </style>
</head>
<body>
    @if (ViewBag.wronglog != null)
    {
        <h1 class="alert alert-danger " style="z-index:5;margin:10px;">@ViewBag.wronglog</h1>
    }
    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>
    <form asp-action="Login" method="post">
        <h3>Login Here</h3>
        @* <input asp-for="Id" value="@Model.Id" type="hidden" class="form-control" /> *@
        <label for="username">Username</label>
        <input type="text" placeholder="Email or Phone" id="username" asp-for="@Model.Name">

        <label for="password">Password</label>
        <input type="password" placeholder="Password" id="password" asp-for="@Model.Password">

        <label for="role">Role</label>
        <select class="custom-select" style="color:black" id="role" asp-for="@Model.role">
            <option value="" disabled style="color:black" selected hidden>Choose a Role</option>
            <option style="color:black" value="user">user</option>
            <option style="color:black" value="seller">seller</option>
        </select>
        <button>Log In</button>
        <div class="social">
            <div class="go"><i class="fab fa-google"></i>  Google</div>
            <div class="fb"><i class="fab fa-facebook"></i>  Facebook</div>
        </div>
    </form>
</body>
</html>

Views/Home/SellerIndex.cshtml
@model IEnumerable<ITI_Project.Models.Product>

@{
    ViewData["Title"] = "Home Page";
}

<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">ITI-Ecommerce For Sellers</h1>
            <p class="lead fw-normal text-white-50 mb-0">Put your product and we will sell it for you</p>
        </div>
    </div>
</header>
<!-- Section-->
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="container text-center">
            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent text-center">
                <a style="margin-right:5%;padding:20px" class="btn btn-outline-success mt-auto" asp-action="CreateProduct" asp-controller="Seller" asp-route-id="@ViewBag.sellerid">Add Product</a>
                <a style="margin-left:5%;padding:20px" class="btn btn-outline-info mt-auto" asp-route-id="@ViewBag.sellerid" asp-controller="Seller" asp-action="Details">my Details</a>
            </div>
        </div>
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            @foreach (var item in Model)
            {
                <div class="col mb-5">
                    <div class="card h-100">
                        <!-- Product image-->
                        <img class="card-img-top" src="/assets/@item.ImageUrl" alt="..." style="height: 100%;" />
                        <!-- Product details-->
                        <div class="card-body p-4">
                            <div class="text-center">
                                <!-- Product name-->
                                <h5 class="fw-bolder">@item.Name</h5>
                                <!-- Product Quantity-->
                                @if (item.Quantity > 3)
                                {
                                    <div class="d-flex justify-content-center small text-success mb-2">
                                        Quantity : @item.Quantity
                                    </div>
                                }
                                else
                                {
                                    <div class="d-flex justify-content-center small text-danger mb-2">
                                        Quantity : @item.Quantity
                                    </div>
                                }

                                <!-- Product price-->
                                @item.Price$
                            </div>
                        </div>
                        <!-- Product actions-->
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center">
                                <a class="btn btn-outline-dark mt-auto" asp-route-id="@item.Id" asp-action="EditProduct" asp-controller="Seller">Edit Product</a>
                            </div>
                            <div class="text-center">
                                <a class="btn btn-outline-danger mt-3" asp-route-id="@item.Id" asp-action="DeleteProduct" asp-controller="Seller">remove Product</a>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</section>

Views/Home/UserIndex.cshtml
@model IEnumerable<ITI_Project.Models.Product>

@{
    ViewData["Title"] = "Home Page";
}

<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">ITI-Ecommerce For Users</h1>
            <p class="lead fw-normal text-white-50 mb-0">All you need is here</p>
        </div>
    </div>
</header>
<div class="container mt-5 text-center">
    <a class="btn btn-success mt-auto" asp-controller="User" asp-action="ViewCart" style="padding:20px;font-weight: 900;">View Cart</a>
</div>
<!-- Section-->
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            @foreach (var item in Model)
            {
                if (item.Quantity > 0)
                {
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="/assets/@item.ImageUrl" alt="..." style="height: 100%;" />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">@item.Name</h5>
                                    <!-- Product Quantity-->
                                    @if (item.Quantity > 3)
                                    {
                                        <div class="d-flex justify-content-center small text-success mb-2">
                                            Quantity : @item.Quantity
                                        </div>
                                    }
                                    else
                                    {
                                        <div class="d-flex justify-content-center small text-danger mb-2">
                                            Quantity : @item.Quantity
                                        </div>
                                    }

                                    <!-- Product price-->
                                    @item.Price $
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" asp-route-productid="@item.Id" asp-action="AddToCart" asp-controller="User">Add to cart</a></div>
                            </div>
                        </div>
                    </div>
                }
                
            }
        </div>
    </div>
</section>